server:
  port: ${SERVER_PORT:8001}

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

security:
  jwt:
    key-store: classpath:JWTKeystore.p12
    key-store-password: devdcorespass
    key-pair-alias: jwt-key
    key-pair-password: devdcorespass
    public-key: classpath:jwt-signing-public-key.txt

tmp:
  user:
    username: admin
    password: $2a$10$RcdUkMLOom4MIeZFkAqzsu0/q6ee8HrK3DhYgFV9WmiompdXLr82u