server:
  port: ${SERVER_PORT:8000}

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-service-discovery:8761/eureka

ribbon:
  eureka:
    enabled: true

spring:
  datasource:
    url: jdbc:postgresql://db-postgresql-nyc1-72839-do-user-7759268-0.a.db.ondigitalocean.com:25060/defaultdb
    username: doadmin
    password: g0ij0n3nj2rpn9oa
    tomcat:
      initial-size: 5
      max-wait: 60000
      max-active: 5
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:liquibase/changelog-master.xml



scheduler:
  stock:
    cron: 0 0/22 * * * *

rabbitmq:
  stock:
    mail: stock_email_queue