server:
  port: ${SERVER_PORT:8005}

spring:
  datasource:
    url: jdbc:postgresql://db-postgresql-nyc1-72839-do-user-7759268-0.a.db.ondigitalocean.com:25060/defaultdb
    username: doadmin
    password: g0ij0n3nj2rpn9oa
    tomcat:
      initial-size: 5
      max-wait: 60000
      max-active: 5
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:liquibase/changelog-master.xml